In [1]:
from environ import PortfolioEnv
from data import MultiAssetData

In [2]:
env_params = {
    # environment related
    'tickers': ['aapl', 'amzn'],
    'mode': "train",
    'random_offset': True,
    'dim_mode': 1,
    # state related
    'commission': 0.01,
    'window_size': 10,
    'cash': False,
    'norm_func': 'softmax'
}

In [3]:
train_data = MultiAssetData(
    ['aapl', 'amzn'],
    daily=False,
    indicators=[],
    news=False,
    mode="train"
)

In [4]:
env = PortfolioEnv(train_data, env_params)

{'tickers': ['aapl', 'amzn'], 'mode': 'train', 'random_offset': True, 'dim_mode': 1, 'commission': 0.01, 'window_size': 10, 'cash': False, 'norm_func': 'softmax'}


In [5]:
eval_data = MultiAssetData(
    ['aapl', 'amzn'],
    daily=False,
    indicators=[],
    news=False,
    mode="val"
)
env_params_val = env_params.copy()
env_params_val['mode'] = 'eval'

In [6]:
env_val = PortfolioEnv(eval_data, env_params_val)

{'tickers': ['aapl', 'amzn'], 'mode': 'eval', 'random_offset': True, 'dim_mode': 1, 'commission': 0.01, 'window_size': 10, 'cash': False, 'norm_func': 'softmax'}


In [7]:
obs = env.reset()
obs

array([ 7.98707362e-04,  0.00000000e+00,  6.93131122e-04,  5.41669905e-01,
        4.37957759e-04, -8.19844776e-04, -8.19844776e-04,  3.03511500e-01,
        6.92616042e-04, -5.04554737e-05,  5.36662759e-04,  3.64850402e-01,
        9.09766357e-04, -2.42604365e-04,  7.42975855e-04,  7.00207949e-02,
        1.05435909e-04, -6.37199613e-04,  0.00000000e+00, -3.30538929e-01,
        3.12124059e-04, -1.09394931e-03, -1.09394931e-03, -2.09274337e-01,
        1.05435909e-04, -2.10871818e-04,  0.00000000e+00,  5.74018396e-02,
        3.48886591e-04, -1.00115279e-03, -1.45622238e-04,  1.88926607e-01,
        3.20891908e-04, -4.26327810e-04, -2.65881856e-04, -2.09704280e-01,
        4.24750848e-04, -1.36527058e-04, -1.36527058e-04, -4.59682971e-01,
        2.75125873e-04, -2.56784144e-04,  1.78831819e-04,  2.77266502e-01,
        6.07164518e-04, -3.03582274e-05,  4.00728604e-04, -2.29956269e-01,
        4.26372746e-04,  0.00000000e+00,  3.20925727e-04,  1.39817372e-01,
        1.01624476e-03, -

In [8]:
idx = env.state.ind
idx

228463

In [9]:
env.state.positions

array([0.5, 0.5])

In [10]:
obs[:-2]

array([ 7.98707362e-04,  0.00000000e+00,  6.93131122e-04,  5.41669905e-01,
        4.37957759e-04, -8.19844776e-04, -8.19844776e-04,  3.03511500e-01,
        6.92616042e-04, -5.04554737e-05,  5.36662759e-04,  3.64850402e-01,
        9.09766357e-04, -2.42604365e-04,  7.42975855e-04,  7.00207949e-02,
        1.05435909e-04, -6.37199613e-04,  0.00000000e+00, -3.30538929e-01,
        3.12124059e-04, -1.09394931e-03, -1.09394931e-03, -2.09274337e-01,
        1.05435909e-04, -2.10871818e-04,  0.00000000e+00,  5.74018396e-02,
        3.48886591e-04, -1.00115279e-03, -1.45622238e-04,  1.88926607e-01,
        3.20891908e-04, -4.26327810e-04, -2.65881856e-04, -2.09704280e-01,
        4.24750848e-04, -1.36527058e-04, -1.36527058e-04, -4.59682971e-01,
        2.75125873e-04, -2.56784144e-04,  1.78831819e-04,  2.77266502e-01,
        6.07164518e-04, -3.03582274e-05,  4.00728604e-04, -2.29956269e-01,
        4.26372746e-04,  0.00000000e+00,  3.20925727e-04,  1.39817372e-01,
        1.01624476e-03, -

In [11]:
env.state.findata.relative_prices.iloc[idx-10+1:idx+1,1:].values.reshape(-1)

array([ 7.98707379e-04,  0.00000000e+00,  6.93131117e-04,  5.41669914e-01,
        4.37957753e-04, -8.19844790e-04, -8.19844790e-04,  3.03511490e-01,
        6.92616071e-04, -5.04554753e-05,  5.36662783e-04,  3.64850405e-01,
        9.09766342e-04, -2.42604358e-04,  7.42975846e-04,  7.00207983e-02,
        1.05435909e-04, -6.37199622e-04,  0.00000000e+00, -3.30538922e-01,
        3.12124050e-04, -1.09394934e-03, -1.09394934e-03, -2.09274343e-01,
        1.05435909e-04, -2.10871817e-04,  0.00000000e+00,  5.74018405e-02,
        3.48886597e-04, -1.00115284e-03, -1.45622232e-04,  1.88926607e-01,
        3.20891896e-04, -4.26327805e-04, -2.65881857e-04, -2.09704284e-01,
        4.24750838e-04, -1.36527055e-04, -1.36527055e-04, -4.59682977e-01,
        2.75125870e-04, -2.56784145e-04,  1.78831816e-04,  2.77266508e-01,
        6.07164542e-04, -3.03582271e-05,  4.00728597e-04, -2.29956268e-01,
        4.26372760e-04,  0.00000000e+00,  3.20925733e-04,  1.39817367e-01,
        1.01624475e-03, -

In [12]:
obs[-2:]

array([0.5, 0.5], dtype=float32)

In [13]:
env.state.last_adj_close_price

array([ 21.8198, 659.08  ], dtype=float32)

In [14]:
env.state.findata.price_data.iloc[idx].loc[[f'{tick}_close_1min' for tick in ['aapl', 'amzn']]]

aapl_close_1min    21.7771
amzn_close_1min     658.95
Name: 228463, dtype: object

In [15]:
env.state.findata.price_data.iloc[idx-2:idx+1]

time  aapl_open_1min  aapl_high_1min  \
228461  2016-04-29 13:25:00-04:00         21.8189         21.8298   
228462  2016-04-29 13:26:00-04:00         21.8279         21.8351   
228463  2016-04-29 13:27:00-04:00         21.8189         21.8200   

        aapl_low_1min  aapl_close_1min  aapl_volume_1min  amzn_open_1min  \
228461        21.8119          21.8261           1185052         659.685   
228462        21.8189          21.8198            364400         659.330   
228463        21.7747          21.7771            433288         659.120   

        amzn_high_1min  amzn_low_1min  amzn_close_1min  amzn_volume_1min  
228461         659.685        659.030           659.44            2668.0  
228462         659.610        658.973           659.08            7070.0  
228463         659.230        658.740           658.95            5983.0

In [16]:
import numpy as np
action = np.array([0.7, 0.3, 0.7])

In [17]:
obs, r, done, info = env.step(np.array([0.7, 0.3, 0.7]))

In [18]:
obs, r, done, info

(array([ 6.92616042e-04, -5.04554737e-05,  5.36662759e-04,  3.64850402e-01,
         9.09766357e-04, -2.42604365e-04,  7.42975855e-04,  7.00207949e-02,
         1.05435909e-04, -6.37199613e-04,  0.00000000e+00, -3.30538929e-01,
         3.12124059e-04, -1.09394931e-03, -1.09394931e-03, -2.09274337e-01,
         1.05435909e-04, -2.10871818e-04,  0.00000000e+00,  5.74018396e-02,
         3.48886591e-04, -1.00115279e-03, -1.45622238e-04,  1.88926607e-01,
         3.20891908e-04, -4.26327810e-04, -2.65881856e-04, -2.09704280e-01,
         4.24750848e-04, -1.36527058e-04, -1.36527058e-04, -4.59682971e-01,
         2.75125873e-04, -2.56784144e-04,  1.78831819e-04,  2.77266502e-01,
         6.07164518e-04, -3.03582274e-05,  4.00728604e-04, -2.29956269e-01,
         4.26372746e-04,  0.00000000e+00,  3.20925727e-04,  1.39817372e-01,
         1.01624476e-03, -1.04658044e-04,  7.73559441e-04, -1.00567915e-01,
         4.99566901e-04, -3.20822786e-04,  3.29989125e-04,  1.24552238e+00,
         0.0

In [19]:
idx = env.state.ind
idx

228464

In [22]:
env.state.findata.relative_prices.iloc[idx-10+1:idx+1,1:].values.reshape(-1)

array([ 1.13869896e-03, -8.85654743e-05,  7.88051975e-04,  2.04802788e+00,
        1.12816991e-03,  0.00000000e+00,  4.61078138e-04,  9.72497250e-01,
        3.07026020e-04, -8.66896996e-05, -8.66896996e-05, -2.17466945e-01,
        1.47120845e-04, -6.76755887e-04, -4.51170592e-04, -5.75432236e-01,
        8.75965142e-04,  0.00000000e+00,  7.00772114e-04,  6.35266468e-01,
        9.71350078e-04,  0.00000000e+00,  9.71350078e-04,  3.61247947e-01,
        4.33163738e-05, -6.56965002e-04, -6.56965002e-04, -4.19864823e-01,
        0.00000000e+00, -1.01950789e-03, -9.21478286e-04, -3.01688782e-01,
        4.37021894e-04, -1.96840440e-04,  3.75622124e-04, -3.31726370e-01,
        2.25614063e-04, -2.69755944e-04,  2.25614063e-04, -8.18621524e-01,
        4.38655080e-04, -1.31777040e-04, -8.66479170e-05,  1.70596487e-01,
        2.45182170e-05, -2.45182170e-04, -2.15760310e-04,  4.16666667e+00,
        3.12308756e-04, -1.26367705e-04,  3.12308756e-04, -4.22938659e-01,
        2.50222011e-04, -

In [24]:
env.state.findata.price_data.iloc[idx-3:idx+1]

time  aapl_open_1min  aapl_high_1min  \
459092  2018-09-04 13:07:00-04:00         55.3939         55.4112   
459093  2018-09-04 13:08:00-04:00         55.4136         55.4160   
459094  2018-09-04 13:09:00-04:00         55.3966         55.4281   
459095  2018-09-04 13:10:00-04:00         55.4257         55.4475   

        aapl_low_1min  aapl_close_1min  aapl_volume_1min  amzn_open_1min  \
459092        55.3869          55.4112             80904         2038.19   
459093        55.3942          55.3966            156264         2038.54   
459094        55.3966          55.4257            105944         2037.65   
459095        55.4257          55.4369            133192         2038.56   

        amzn_high_1min  amzn_low_1min  amzn_close_1min  amzn_volume_1min  
459092         2038.70        2037.54          2038.47            5019.0  
459093         2038.54        2037.99          2038.04            1513.0  
459094         2038.14        2037.16          2037.73            5625.0  
459095         2039.45        2038.37          2038.37            7126.0

In [38]:
[env.state.findata.price_data.iloc[idx-3].loc[f'{ticker}_close_1min'] for ticker in ['aapl', 'amzn']]

[36.2823, 993.11]

In [40]:
env.state.last_adj_close_price

array([ 36.2658, 993.264 ], dtype=float32)